const cityList = [ { id: 0, city: 'Abilene', state: 'TX', value: 'Abilene, TX' },
  { id: 1, city: 'Addison', state: 'IL', value: 'Addison, IL' },
  { id: 2, city: 'Akron', state: 'OH', value: 'Akron, OH' },
  { id: 3, city: 'Alameda', state: 'CA', value: 'Alameda, CA' },
  { id: 4, city: 'Albany', state: 'NY', value: 'Albany, NY' },
  { id: 5, city: 'Albany', state: 'GA', value: 'Albany, GA' },
  { id: 6, city: 'Albany', state: 'OR', value: 'Albany, OR' },
  { id: 7,
    city: 'Albuquerque',
    state: 'NM',
    value: 'Albuquerque, NM' },
  { id: 8,
    city: 'Alexandria',
    state: 'VA',
    value: 'Alexandria, VA' },
  { id: 9,
    city: 'Alexandria',
    state: 'LA',
    value: 'Alexandria, LA' },
  { id: 10, city: 'Alhambra', state: 'CA', value: 'Alhambra, CA' },
  { id: 11,
    city: 'Aliso Viejo',
    state: 'CA',
    value: 'Aliso Viejo, CA' },
  { id: 12, city: 'Allen', state: 'TX', value: 'Allen, TX' },
  { id: 13, city: 'Allentown', state: 'PA', value: 'Allentown, PA' },
  { id: 14,
    city: 'Alpharetta',
    state: 'GA',
    value: 'Alpharetta, GA' },
  { id: 15,
    city: 'Altamonte Springs',
    state: 'FL',
    value: 'Altamonte Springs, FL' },
  { id: 16, city: 'Altoona', state: 'PA', value: 'Altoona, PA' },
  { id: 17, city: 'Amarillo', state: 'TX', value: 'Amarillo, TX' },
  { id: 18, city: 'Ames', state: 'IA', value: 'Ames, IA' },
  { id: 19, city: 'Anaheim', state: 'CA', value: 'Anaheim, CA' },
  { id: 20, city: 'Anchorage', state: 'AK', value: 'Anchorage, AK' },
  { id: 21, city: 'Anderson', state: 'IN', value: 'Anderson, IN' },
  { id: 22, city: 'Ankeny', state: 'IA', value: 'Ankeny, IA' },
  { id: 23, city: 'Ann Arbor', state: 'MI', value: 'Ann Arbor, MI' },
  { id: 24, city: 'Annapolis', state: 'MD', value: 'Annapolis, MD' },
  { id: 25, city: 'Antioch', state: 'CA', value: 'Antioch, CA' },
  { id: 26,
    city: 'Apache Junction',
    state: 'AZ',
    value: 'Apache Junction, AZ' },
  { id: 27, city: 'Apex', state: 'NC', value: 'Apex, NC' },
  { id: 28, city: 'Apopka', state: 'FL', value: 'Apopka, FL' },
  { id: 29,
    city: 'Apple Valley',
    state: 'CA',
    value: 'Apple Valley, CA' },
  { id: 30,
    city: 'Apple Valley',
    state: 'MN',
    value: 'Apple Valley, MN' },
  { id: 31, city: 'Appleton', state: 'WI', value: 'Appleton, WI' },
  { id: 32, city: 'Arcadia', state: 'CA', value: 'Arcadia, CA' },
  { id: 33, city: 'Arlington', state: 'TX', value: 'Arlington, TX' },
  { id: 34,
    city: 'Arlington Heights',
    state: 'IL',
    value: 'Arlington Heights, IL' },
  { id: 35, city: 'Arvada', state: 'CO', value: 'Arvada, CO' },
  { id: 36, city: 'Asheville', state: 'NC', value: 'Asheville, NC' },
  { id: 37,
    city: 'Athens-Clarke County',
    state: 'GA',
    value: 'Athens-Clarke County, GA' },
  { id: 38, city: 'Atlanta', state: 'GA', value: 'Atlanta, GA' },
  { id: 39,
    city: 'Atlantic City',
    state: 'NJ',
    value: 'Atlantic City, NJ' },
  { id: 40, city: 'Attleboro', state: 'MA', value: 'Attleboro, MA' },
  { id: 41, city: 'Auburn', state: 'WA', value: 'Auburn, WA' },
  { id: 42, city: 'Auburn', state: 'AL', value: 'Auburn, AL' },
  { id: 43,
    city: 'Augusta-Richmond County',
    state: 'GA',
    value: 'Augusta-Richmond County, GA' },
  { id: 44, city: 'Aurora', state: 'CO', value: 'Aurora, CO' },
  { id: 45, city: 'Aurora', state: 'IL', value: 'Aurora, IL' },
  { id: 46, city: 'Austin', state: 'TX', value: 'Austin, TX' },
  { id: 47, city: 'Aventura', state: 'FL', value: 'Aventura, FL' },
  { id: 48, city: 'Avondale', state: 'AZ', value: 'Avondale, AZ' },
  { id: 49, city: 'Azusa', state: 'CA', value: 'Azusa, CA' },
  { id: 50,
    city: 'Bakersfield',
    state: 'CA',
    value: 'Bakersfield, CA' },
  { id: 51,
    city: 'Baldwin Park',
    state: 'CA',
    value: 'Baldwin Park, CA' },
  { id: 52, city: 'Baltimore', state: 'MD', value: 'Baltimore, MD' },
  { id: 53,
    city: 'Barnstable Town',
    state: 'MA',
    value: 'Barnstable Town, MA' },
  { id: 54, city: 'Bartlett', state: 'TN', value: 'Bartlett, TN' },
  { id: 55, city: 'Bartlett', state: 'IL', value: 'Bartlett, IL' },
  { id: 56,
    city: 'Baton Rouge',
    state: 'LA',
    value: 'Baton Rouge, LA' },
  { id: 57,
    city: 'Battle Creek',
    state: 'MI',
    value: 'Battle Creek, MI' },
  { id: 58, city: 'Bayonne', state: 'NJ', value: 'Bayonne, NJ' },
  { id: 59, city: 'Baytown', state: 'TX', value: 'Baytown, TX' },
  { id: 60, city: 'Beaumont', state: 'TX', value: 'Beaumont, TX' },
  { id: 61, city: 'Beaumont', state: 'CA', value: 'Beaumont, CA' },
  { id: 62,
    city: 'Beavercreek',
    state: 'OH',
    value: 'Beavercreek, OH' },
  { id: 63, city: 'Beaverton', state: 'OR', value: 'Beaverton, OR' },
  { id: 64, city: 'Bedford', state: 'TX', value: 'Bedford, TX' },
  { id: 65,
    city: 'Bell Gardens',
    state: 'CA',
    value: 'Bell Gardens, CA' },
  { id: 66,
    city: 'Belleville',
    state: 'IL',
    value: 'Belleville, IL' },
  { id: 67, city: 'Bellevue', state: 'WA', value: 'Bellevue, WA' },
  { id: 68, city: 'Bellevue', state: 'NE', value: 'Bellevue, NE' },
  { id: 69,
    city: 'Bellflower',
    state: 'CA',
    value: 'Bellflower, CA' },
  { id: 70,
    city: 'Bellingham',
    state: 'WA',
    value: 'Bellingham, WA' },
  { id: 71, city: 'Beloit', state: 'WI', value: 'Beloit, WI' },
  { id: 72, city: 'Bend', state: 'OR', value: 'Bend, OR' },
  { id: 73,
    city: 'Bentonville',
    state: 'AR',
    value: 'Bentonville, AR' },
  { id: 74, city: 'Berkeley', state: 'CA', value: 'Berkeley, CA' },
  { id: 75, city: 'Berwyn', state: 'IL', value: 'Berwyn, IL' },
  { id: 76, city: 'Bethlehem', state: 'PA', value: 'Bethlehem, PA' },
  { id: 77, city: 'Beverly', state: 'MA', value: 'Beverly, MA' },
  { id: 78, city: 'Billings', state: 'MT', value: 'Billings, MT' },
  { id: 79, city: 'Biloxi', state: 'MS', value: 'Biloxi, MS' },
  { id: 80,
    city: 'Binghamton',
    state: 'NY',
    value: 'Binghamton, NY' },
  { id: 81,
    city: 'Birmingham',
    state: 'AL',
    value: 'Birmingham, AL' },
  { id: 82, city: 'Bismarck', state: 'ND', value: 'Bismarck, ND' },
  { id: 83,
    city: 'Blacksburg',
    state: 'VA',
    value: 'Blacksburg, VA' },
  { id: 84, city: 'Blaine', state: 'MN', value: 'Blaine, MN' },
  { id: 85,
    city: 'Bloomington',
    state: 'MN',
    value: 'Bloomington, MN' },
  { id: 86,
    city: 'Bloomington',
    state: 'IN',
    value: 'Bloomington, IN' },
  { id: 87,
    city: 'Bloomington',
    state: 'IL',
    value: 'Bloomington, IL' },
  { id: 88,
    city: 'Blue Springs',
    state: 'MO',
    value: 'Blue Springs, MO' },
  { id: 89,
    city: 'Boca Raton',
    state: 'FL',
    value: 'Boca Raton, FL' },
  { id: 90,
    city: 'Boise City',
    state: 'ID',
    value: 'Boise City, ID' },
  { id: 91,
    city: 'Bolingbrook',
    state: 'IL',
    value: 'Bolingbrook, IL' },
  { id: 92,
    city: 'Bonita Springs',
    state: 'FL',
    value: 'Bonita Springs, FL' },
  { id: 93,
    city: 'Bossier City',
    state: 'LA',
    value: 'Bossier City, LA' },
  { id: 94, city: 'Boston', state: 'MA', value: 'Boston, MA' },
  { id: 95, city: 'Boulder', state: 'CO', value: 'Boulder, CO' },
  { id: 96, city: 'Bountiful', state: 'UT', value: 'Bountiful, UT' },
  { id: 97, city: 'Bowie', state: 'MD', value: 'Bowie, MD' },
  { id: 98,
    city: 'Bowling Green',
    state: 'KY',
    value: 'Bowling Green, KY' },
  { id: 99,
    city: 'Boynton Beach',
    state: 'FL',
    value: 'Boynton Beach, FL' },
  { id: 100, city: 'Bozeman', state: 'MT', value: 'Bozeman, MT' },
  { id: 101,
    city: 'Bradenton',
    state: 'FL',
    value: 'Bradenton, FL' },
  { id: 102, city: 'Brea', state: 'CA', value: 'Brea, CA' },
  { id: 103,
    city: 'Bremerton',
    state: 'WA',
    value: 'Bremerton, WA' },
  { id: 104,
    city: 'Brentwood',
    state: 'CA',
    value: 'Brentwood, CA' },
  { id: 105,
    city: 'Brentwood',
    state: 'TN',
    value: 'Brentwood, TN' },
  { id: 106,
    city: 'Bridgeport',
    state: 'CT',
    value: 'Bridgeport, CT' },
  { id: 107, city: 'Bristol', state: 'CT', value: 'Bristol, CT' },
  { id: 108, city: 'Brockton', state: 'MA', value: 'Brockton, MA' },
  { id: 109,
    city: 'Broken Arrow',
    state: 'OK',
    value: 'Broken Arrow, OK' },
  { id: 110,
    city: 'Brookfield',
    state: 'WI',
    value: 'Brookfield, WI' },
  { id: 111,
    city: 'Brookhaven',
    state: 'GA',
    value: 'Brookhaven, GA' },
  { id: 112,
    city: 'Brooklyn Park',
    state: 'MN',
    value: 'Brooklyn Park, MN' },
  { id: 113,
    city: 'Broomfield',
    state: 'CO',
    value: 'Broomfield, CO' },
  { id: 114,
    city: 'Brownsville',
    state: 'TX',
    value: 'Brownsville, TX' },
  { id: 115, city: 'Bryan', state: 'TX', value: 'Bryan, TX' },
  { id: 116, city: 'Buckeye', state: 'AZ', value: 'Buckeye, AZ' },
  { id: 117,
    city: 'Buena Park',
    state: 'CA',
    value: 'Buena Park, CA' },
  { id: 118, city: 'Buffalo', state: 'NY', value: 'Buffalo, NY' },
  { id: 119,
    city: 'Buffalo Grove',
    state: 'IL',
    value: 'Buffalo Grove, IL' },
  { id: 120,
    city: 'Bullhead City',
    state: 'AZ',
    value: 'Bullhead City, AZ' },
  { id: 121, city: 'Burbank', state: 'CA', value: 'Burbank, CA' },
  { id: 122, city: 'Burien', state: 'WA', value: 'Burien, WA' },
  { id: 123, city: 'Burleson', state: 'TX', value: 'Burleson, TX' },
  { id: 124,
    city: 'Burlington',
    state: 'NC',
    value: 'Burlington, NC' },
  { id: 125,
    city: 'Burlington',
    state: 'VT',
    value: 'Burlington, VT' },
  { id: 126,
    city: 'Burnsville',
    state: 'MN',
    value: 'Burnsville, MN' },
  { id: 127, city: 'Caldwell', state: 'ID', value: 'Caldwell, ID' },
  { id: 128, city: 'Calexico', state: 'CA', value: 'Calexico, CA' },
  { id: 129,
    city: 'Calumet City',
    state: 'IL',
    value: 'Calumet City, IL' },
  { id: 130,
    city: 'Camarillo',
    state: 'CA',
    value: 'Camarillo, CA' },
  { id: 131,
    city: 'Cambridge',
    state: 'MA',
    value: 'Cambridge, MA' },
  { id: 132, city: 'Camden', state: 'NJ', value: 'Camden, NJ' },
  { id: 133, city: 'Campbell', state: 'CA', value: 'Campbell, CA' },
  { id: 134, city: 'Canton', state: 'OH', value: 'Canton, OH' },
  { id: 135,
    city: 'Cape Coral',
    state: 'FL',
    value: 'Cape Coral, FL' },
  { id: 136,
    city: 'Cape Girardeau',
    state: 'MO',
    value: 'Cape Girardeau, MO' },
  { id: 137, city: 'Carlsbad', state: 'CA', value: 'Carlsbad, CA' },
  { id: 138, city: 'Carmel', state: 'IN', value: 'Carmel, IN' },
  { id: 139,
    city: 'Carol Stream',
    state: 'IL',
    value: 'Carol Stream, IL' },
  { id: 140,
    city: 'Carpentersville',
    state: 'IL',
    value: 'Carpentersville, IL' },
  { id: 141,
    city: 'Carrollton',
    state: 'TX',
    value: 'Carrollton, TX' },
  { id: 142, city: 'Carson', state: 'CA', value: 'Carson, CA' },
  { id: 143,
    city: 'Carson City',
    state: 'NV',
    value: 'Carson City, NV' },
  { id: 144, city: 'Cary', state: 'NC', value: 'Cary, NC' },
  { id: 145,
    city: 'Casa Grande',
    state: 'AZ',
    value: 'Casa Grande, AZ' },
  { id: 146, city: 'Casper', state: 'WY', value: 'Casper, WY' },
  { id: 147,
    city: 'Castle Rock',
    state: 'CO',
    value: 'Castle Rock, CO' },
  { id: 148,
    city: 'Cathedral City',
    state: 'CA',
    value: 'Cathedral City, CA' },
  { id: 149,
    city: 'Cedar Falls',
    state: 'IA',
    value: 'Cedar Falls, IA' },
  { id: 150,
    city: 'Cedar Hill',
    state: 'TX',
    value: 'Cedar Hill, TX' },
  { id: 151,
    city: 'Cedar Park',
    state: 'TX',
    value: 'Cedar Park, TX' },
  { id: 152,
    city: 'Cedar Rapids',
    state: 'IA',
    value: 'Cedar Rapids, IA' },
  { id: 153,
    city: 'Centennial',
    state: 'CO',
    value: 'Centennial, CO' },
  { id: 154, city: 'Ceres', state: 'CA', value: 'Ceres, CA' },
  { id: 155, city: 'Cerritos', state: 'CA', value: 'Cerritos, CA' },
  { id: 156,
    city: 'Champaign',
    state: 'IL',
    value: 'Champaign, IL' },
  { id: 157, city: 'Chandler', state: 'AZ', value: 'Chandler, AZ' },
  { id: 158,
    city: 'Chapel Hill',
    state: 'NC',
    value: 'Chapel Hill, NC' },
  { id: 159,
    city: 'Charleston',
    state: 'SC',
    value: 'Charleston, SC' },
  { id: 160,
    city: 'Charleston',
    state: 'WV',
    value: 'Charleston, WV' },
  { id: 161,
    city: 'Charlotte',
    state: 'NC',
    value: 'Charlotte, NC' },
  { id: 162,
    city: 'Charlottesville',
    state: 'VA',
    value: 'Charlottesville, VA' },
  { id: 163,
    city: 'Chattanooga',
    state: 'TN',
    value: 'Chattanooga, TN' },
  { id: 164, city: 'Chelsea', state: 'MA', value: 'Chelsea, MA' },
  { id: 165,
    city: 'Chesapeake',
    state: 'VA',
    value: 'Chesapeake, VA' },
  { id: 166,
    city: 'Chesterfield',
    state: 'MO',
    value: 'Chesterfield, MO' },
  { id: 167, city: 'Cheyenne', state: 'WY', value: 'Cheyenne, WY' },
  { id: 168, city: 'Chicago', state: 'IL', value: 'Chicago, IL' },
  { id: 169, city: 'Chico', state: 'CA', value: 'Chico, CA' },
  { id: 170, city: 'Chicopee', state: 'MA', value: 'Chicopee, MA' },
  { id: 171, city: 'Chino', state: 'CA', value: 'Chino, CA' },
  { id: 172,
    city: 'Chino Hills',
    state: 'CA',
    value: 'Chino Hills, CA' },
  { id: 173,
    city: 'Chula Vista',
    state: 'CA',
    value: 'Chula Vista, CA' },
  { id: 174, city: 'Cicero', state: 'IL', value: 'Cicero, IL' },
  { id: 175,
    city: 'Cincinnati',
    state: 'OH',
    value: 'Cincinnati, OH' },
  { id: 176,
    city: 'Citrus Heights',
    state: 'CA',
    value: 'Citrus Heights, CA' },
  { id: 177,
    city: 'Clarksville',
    state: 'TN',
    value: 'Clarksville, TN' },
  { id: 178,
    city: 'Clearwater',
    state: 'FL',
    value: 'Clearwater, FL' },
  { id: 179,
    city: 'Cleveland',
    state: 'OH',
    value: 'Cleveland, OH' },
  { id: 180,
    city: 'Cleveland',
    state: 'TN',
    value: 'Cleveland, TN' },
  { id: 181,
    city: 'Cleveland Heights',
    state: 'OH',
    value: 'Cleveland Heights, OH' },
  { id: 182, city: 'Clifton', state: 'NJ', value: 'Clifton, NJ' },
  { id: 183, city: 'Clovis', state: 'CA', value: 'Clovis, CA' },
  { id: 184, city: 'Clovis', state: 'NM', value: 'Clovis, NM' },
  { id: 185,
    city: 'Coachella',
    state: 'CA',
    value: 'Coachella, CA' },
  { id: 186,
    city: 'Coconut Creek',
    state: 'FL',
    value: 'Coconut Creek, FL' },
  { id: 187,
    city: 'Coeur d\'Alene',
    state: 'ID',
    value: 'Coeur d\'Alene, ID' },
  { id: 188,
    city: 'College Station',
    state: 'TX',
    value: 'College Station, TX' },
  { id: 189,
    city: 'Collierville',
    state: 'TN',
    value: 'Collierville, TN' },
  { id: 190,
    city: 'Colorado Springs',
    state: 'CO',
    value: 'Colorado Springs, CO' },
  { id: 191, city: 'Colton', state: 'CA', value: 'Colton, CA' },
  { id: 192, city: 'Columbia', state: 'SC', value: 'Columbia, SC' },
  { id: 193, city: 'Columbia', state: 'MO', value: 'Columbia, MO' },
  { id: 194, city: 'Columbus', state: 'OH', value: 'Columbus, OH' },
  { id: 195, city: 'Columbus', state: 'GA', value: 'Columbus, GA' },
  { id: 196, city: 'Columbus', state: 'IN', value: 'Columbus, IN' },
  { id: 197,
    city: 'Commerce City',
    state: 'CO',
    value: 'Commerce City, CO' },
  { id: 198, city: 'Compton', state: 'CA', value: 'Compton, CA' },
  { id: 199, city: 'Concord', state: 'CA', value: 'Concord, CA' },
  { id: 200, city: 'Concord', state: 'NC', value: 'Concord, NC' },
  { id: 201, city: 'Concord', state: 'NH', value: 'Concord, NH' },
  { id: 202, city: 'Conroe', state: 'TX', value: 'Conroe, TX' },
  { id: 203, city: 'Conway', state: 'AR', value: 'Conway, AR' },
  { id: 204,
    city: 'Coon Rapids',
    state: 'MN',
    value: 'Coon Rapids, MN' },
  { id: 205, city: 'Coppell', state: 'TX', value: 'Coppell, TX' },
  { id: 206,
    city: 'Coral Gables',
    state: 'FL',
    value: 'Coral Gables, FL' },
  { id: 207,
    city: 'Coral Springs',
    state: 'FL',
    value: 'Coral Springs, FL' },
  { id: 208, city: 'Corona', state: 'CA', value: 'Corona, CA' },
  { id: 209,
    city: 'Corpus Christi',
    state: 'TX',
    value: 'Corpus Christi, TX' },
  { id: 210,
    city: 'Corvallis',
    state: 'OR',
    value: 'Corvallis, OR' },
  { id: 211,
    city: 'Costa Mesa',
    state: 'CA',
    value: 'Costa Mesa, CA' },
  { id: 212,
    city: 'Council Bluffs',
    state: 'IA',
    value: 'Council Bluffs, IA' },
  { id: 213, city: 'Covina', state: 'CA', value: 'Covina, CA' },
  { id: 214,
    city: 'Covington',
    state: 'KY',
    value: 'Covington, KY' },
  { id: 215, city: 'Cranston', state: 'RI', value: 'Cranston, RI' },
  { id: 216,
    city: 'Crystal Lake',
    state: 'IL',
    value: 'Crystal Lake, IL' },
  { id: 217,
    city: 'Culver City',
    state: 'CA',
    value: 'Culver City, CA' },
  { id: 218,
    city: 'Cupertino',
    state: 'CA',
    value: 'Cupertino, CA' },
  { id: 219,
    city: 'Cutler Bay',
    state: 'FL',
    value: 'Cutler Bay, FL' },
  { id: 220,
    city: 'Cuyahoga Falls',
    state: 'OH',
    value: 'Cuyahoga Falls, OH' },
  { id: 221, city: 'Cypress', state: 'CA', value: 'Cypress, CA' },
  { id: 222, city: 'Dallas', state: 'TX', value: 'Dallas, TX' },
  { id: 223,
    city: 'Daly City',
    state: 'CA',
    value: 'Daly City, CA' },
  { id: 224, city: 'Danbury', state: 'CT', value: 'Danbury, CT' },
  { id: 225, city: 'Danville', state: 'CA', value: 'Danville, CA' },
  { id: 226, city: 'Danville', state: 'VA', value: 'Danville, VA' },
  { id: 227,
    city: 'Davenport',
    state: 'IA',
    value: 'Davenport, IA' },
  { id: 228, city: 'Davie', state: 'FL', value: 'Davie, FL' },
  { id: 229, city: 'Davis', state: 'CA', value: 'Davis, CA' },
  { id: 230, city: 'Dayton', state: 'OH', value: 'Dayton, OH' },
  { id: 231,
    city: 'Daytona Beach',
    state: 'FL',
    value: 'Daytona Beach, FL' },
  { id: 232, city: 'DeKalb', state: 'IL', value: 'DeKalb, IL' },
  { id: 233, city: 'DeSoto', state: 'TX', value: 'DeSoto, TX' },
  { id: 234, city: 'Dearborn', state: 'MI', value: 'Dearborn, MI' },
  { id: 235,
    city: 'Dearborn Heights',
    state: 'MI',
    value: 'Dearborn Heights, MI' },
  { id: 236, city: 'Decatur', state: 'IL', value: 'Decatur, IL' },
  { id: 237, city: 'Decatur', state: 'AL', value: 'Decatur, AL' },
  { id: 238,
    city: 'Deerfield Beach',
    state: 'FL',
    value: 'Deerfield Beach, FL' },
  { id: 239, city: 'Delano', state: 'CA', value: 'Delano, CA' },
  { id: 240,
    city: 'Delray Beach',
    state: 'FL',
    value: 'Delray Beach, FL' },
  { id: 241, city: 'Deltona', state: 'FL', value: 'Deltona, FL' },
  { id: 242, city: 'Denton', state: 'TX', value: 'Denton, TX' },
  { id: 243, city: 'Denver', state: 'CO', value: 'Denver, CO' },
  { id: 244,
    city: 'Des Moines',
    state: 'IA',
    value: 'Des Moines, IA' },
  { id: 245,
    city: 'Des Plaines',
    state: 'IL',
    value: 'Des Plaines, IL' },
  { id: 246, city: 'Detroit', state: 'MI', value: 'Detroit, MI' },
  { id: 247,
    city: 'Diamond Bar',
    state: 'CA',
    value: 'Diamond Bar, CA' },
  { id: 248, city: 'Doral', state: 'FL', value: 'Doral, FL' },
  { id: 249, city: 'Dothan', state: 'AL', value: 'Dothan, AL' },
  { id: 250, city: 'Dover', state: 'DE', value: 'Dover, DE' },
  { id: 251,
    city: 'Downers Grove',
    state: 'IL',
    value: 'Downers Grove, IL' },
  { id: 252, city: 'Downey', state: 'CA', value: 'Downey, CA' },
  { id: 253, city: 'Draper', state: 'UT', value: 'Draper, UT' },
  { id: 254, city: 'Dublin', state: 'CA', value: 'Dublin, CA' },
  { id: 255, city: 'Dublin', state: 'OH', value: 'Dublin, OH' },
  { id: 256, city: 'Dubuque', state: 'IA', value: 'Dubuque, IA' },
  { id: 257, city: 'Duluth', state: 'MN', value: 'Duluth, MN' },
  { id: 258,
    city: 'Duncanville',
    state: 'TX',
    value: 'Duncanville, TX' },
  { id: 259, city: 'Dunwoody', state: 'GA', value: 'Dunwoody, GA' },
  { id: 260, city: 'Durham', state: 'NC', value: 'Durham, NC' },
  { id: 261, city: 'Eagan', state: 'MN', value: 'Eagan, MN' },
  { id: 262,
    city: 'East Lansing',
    state: 'MI',
    value: 'East Lansing, MI' },
  { id: 263,
    city: 'East Orange',
    state: 'NJ',
    value: 'East Orange, NJ' },
  { id: 264,
    city: 'East Providence',
    state: 'RI',
    value: 'East Providence, RI' },
  { id: 265, city: 'Eastvale', state: 'CA', value: 'Eastvale, CA' },
  { id: 266,
    city: 'Eau Claire',
    state: 'WI',
    value: 'Eau Claire, WI' },
  { id: 267,
    city: 'Eden Prairie',
    state: 'MN',
    value: 'Eden Prairie, MN' },
  { id: 268, city: 'Edina', state: 'MN', value: 'Edina, MN' },
  { id: 269, city: 'Edinburg', state: 'TX', value: 'Edinburg, TX' },
  { id: 270, city: 'Edmond', state: 'OK', value: 'Edmond, OK' },
  { id: 271, city: 'Edmonds', state: 'WA', value: 'Edmonds, WA' },
  { id: 272, city: 'El Cajon', state: 'CA', value: 'El Cajon, CA' },
  { id: 273,
    city: 'El Centro',
    state: 'CA',
    value: 'El Centro, CA' },
  { id: 274, city: 'El Monte', state: 'CA', value: 'El Monte, CA' },
  { id: 275, city: 'El Paso', state: 'TX', value: 'El Paso, TX' },
  { id: 276, city: 'Elgin', state: 'IL', value: 'Elgin, IL' },
  { id: 277,
    city: 'Elizabeth',
    state: 'NJ',
    value: 'Elizabeth, NJ' },
  { id: 278,
    city: 'Elk Grove',
    state: 'CA',
    value: 'Elk Grove, CA' },
  { id: 279, city: 'Elkhart', state: 'IN', value: 'Elkhart, IN' },
  { id: 280, city: 'Elmhurst', state: 'IL', value: 'Elmhurst, IL' },
  { id: 281, city: 'Elyria', state: 'OH', value: 'Elyria, OH' },
  { id: 282,
    city: 'Encinitas',
    state: 'CA',
    value: 'Encinitas, CA' },
  { id: 283, city: 'Enid', state: 'OK', value: 'Enid, OK' },
  { id: 284, city: 'Erie', state: 'PA', value: 'Erie, PA' },
  { id: 285,
    city: 'Escondido',
    state: 'CA',
    value: 'Escondido, CA' },
  { id: 286, city: 'Euclid', state: 'OH', value: 'Euclid, OH' },
  { id: 287, city: 'Eugene', state: 'OR', value: 'Eugene, OR' },
  { id: 288, city: 'Euless', state: 'TX', value: 'Euless, TX' },
  { id: 289, city: 'Evanston', state: 'IL', value: 'Evanston, IL' },
  { id: 290,
    city: 'Evansville',
    state: 'IN',
    value: 'Evansville, IN' },
  { id: 291, city: 'Everett', state: 'WA', value: 'Everett, WA' },
  { id: 292, city: 'Everett', state: 'MA', value: 'Everett, MA' },
  { id: 293,
    city: 'Fairfield',
    state: 'CA',
    value: 'Fairfield, CA' },
  { id: 294,
    city: 'Fairfield',
    state: 'OH',
    value: 'Fairfield, OH' },
  { id: 295,
    city: 'Fall River',
    state: 'MA',
    value: 'Fall River, MA' },
  { id: 296, city: 'Fargo', state: 'ND', value: 'Fargo, ND' },
  { id: 297,
    city: 'Farmington',
    state: 'NM',
    value: 'Farmington, NM' },
  { id: 298,
    city: 'Farmington Hills',
    state: 'MI',
    value: 'Farmington Hills, MI' },
  { id: 299,
    city: 'Fayetteville',
    state: 'NC',
    value: 'Fayetteville, NC' },
  { id: 300,
    city: 'Fayetteville',
    state: 'AR',
    value: 'Fayetteville, AR' },
  { id: 301,
    city: 'Federal Way',
    state: 'WA',
    value: 'Federal Way, WA' },
  { id: 302, city: 'Findlay', state: 'OH', value: 'Findlay, OH' },
  { id: 303, city: 'Fishers', state: 'IN', value: 'Fishers, IN' },
  { id: 304,
    city: 'Fitchburg',
    state: 'MA',
    value: 'Fitchburg, MA' },
  { id: 305,
    city: 'Flagstaff',
    state: 'AZ',
    value: 'Flagstaff, AZ' },
  { id: 306, city: 'Flint', state: 'MI', value: 'Flint, MI' },
  { id: 307, city: 'Florence', state: 'AL', value: 'Florence, AL' },
  { id: 308, city: 'Florence', state: 'SC', value: 'Florence, SC' },
  { id: 309,
    city: 'Florissant',
    state: 'MO',
    value: 'Florissant, MO' },
  { id: 310,
    city: 'Flower Mound',
    state: 'TX',
    value: 'Flower Mound, TX' },
  { id: 311, city: 'Folsom', state: 'CA', value: 'Folsom, CA' },
  { id: 312,
    city: 'Fond du Lac',
    state: 'WI',
    value: 'Fond du Lac, WI' },
  { id: 313, city: 'Fontana', state: 'CA', value: 'Fontana, CA' },
  { id: 314,
    city: 'Fort Collins',
    state: 'CO',
    value: 'Fort Collins, CO' },
  { id: 315,
    city: 'Fort Lauderdale',
    state: 'FL',
    value: 'Fort Lauderdale, FL' },
  { id: 316,
    city: 'Fort Myers',
    state: 'FL',
    value: 'Fort Myers, FL' },
  { id: 317,
    city: 'Fort Pierce',
    state: 'FL',
    value: 'Fort Pierce, FL' },
  { id: 318,
    city: 'Fort Smith',
    state: 'AR',
    value: 'Fort Smith, AR' },
  { id: 319,
    city: 'Fort Wayne',
    state: 'IN',
    value: 'Fort Wayne, IN' },
  { id: 320,
    city: 'Fort Worth',
    state: 'TX',
    value: 'Fort Worth, TX' },
  { id: 321,
    city: 'Fountain Valley',
    state: 'CA',
    value: 'Fountain Valley, CA' },
  { id: 322, city: 'Franklin', state: 'TN', value: 'Franklin, TN' },
  { id: 323,
    city: 'Frederick',
    state: 'MD',
    value: 'Frederick, MD' },
  { id: 324, city: 'Freeport', state: 'NY', value: 'Freeport, NY' },
  { id: 325, city: 'Fremont', state: 'CA', value: 'Fremont, CA' },
  { id: 326, city: 'Fresno', state: 'CA', value: 'Fresno, CA' },
  { id: 327,
    city: 'Friendswood',
    state: 'TX',
    value: 'Friendswood, TX' },
  { id: 328, city: 'Frisco', state: 'TX', value: 'Frisco, TX' },
  { id: 329,
    city: 'Fullerton',
    state: 'CA',
    value: 'Fullerton, CA' },
  { id: 330,
    city: 'Gainesville',
    state: 'FL',
    value: 'Gainesville, FL' },
  { id: 331,
    city: 'Gaithersburg',
    state: 'MD',
    value: 'Gaithersburg, MD' },
  { id: 332,
    city: 'Galveston',
    state: 'TX',
    value: 'Galveston, TX' },
  { id: 333,
    city: 'Garden Grove',
    state: 'CA',
    value: 'Garden Grove, CA' },
  { id: 334, city: 'Gardena', state: 'CA', value: 'Gardena, CA' },
  { id: 335, city: 'Garland', state: 'TX', value: 'Garland, TX' },
  { id: 336, city: 'Gary', state: 'IN', value: 'Gary, IN' },
  { id: 337, city: 'Gastonia', state: 'NC', value: 'Gastonia, NC' },
  { id: 338,
    city: 'Georgetown',
    state: 'TX',
    value: 'Georgetown, TX' },
  { id: 339,
    city: 'Germantown',
    state: 'TN',
    value: 'Germantown, TN' },
  { id: 340, city: 'Gilbert', state: 'AZ', value: 'Gilbert, AZ' },
  { id: 341, city: 'Gilroy', state: 'CA', value: 'Gilroy, CA' },
  { id: 342, city: 'Glendale', state: 'AZ', value: 'Glendale, AZ' },
  { id: 343, city: 'Glendale', state: 'CA', value: 'Glendale, CA' },
  { id: 344, city: 'Glendora', state: 'CA', value: 'Glendora, CA' },
  { id: 345, city: 'Glenview', state: 'IL', value: 'Glenview, IL' },
  { id: 346, city: 'Goodyear', state: 'AZ', value: 'Goodyear, AZ' },
  { id: 347,
    city: 'Goose Creek',
    state: 'SC',
    value: 'Goose Creek, SC' },
  { id: 348,
    city: 'Grand Forks',
    state: 'ND',
    value: 'Grand Forks, ND' },
  { id: 349,
    city: 'Grand Island',
    state: 'NE',
    value: 'Grand Island, NE' },
  { id: 350,
    city: 'Grand Junction',
    state: 'CO',
    value: 'Grand Junction, CO' },
  { id: 351,
    city: 'Grand Prairie',
    state: 'TX',
    value: 'Grand Prairie, TX' },
  { id: 352,
    city: 'Grand Rapids',
    state: 'MI',
    value: 'Grand Rapids, MI' },
  { id: 353,
    city: 'Grapevine',
    state: 'TX',
    value: 'Grapevine, TX' },
  { id: 354,
    city: 'Great Falls',
    state: 'MT',
    value: 'Great Falls, MT' },
  { id: 355, city: 'Greeley', state: 'CO', value: 'Greeley, CO' },
  { id: 356,
    city: 'Green Bay',
    state: 'WI',
    value: 'Green Bay, WI' },
  { id: 357,
    city: 'Greenacres',
    state: 'FL',
    value: 'Greenacres, FL' },
  { id: 358,
    city: 'Greenfield',
    state: 'WI',
    value: 'Greenfield, WI' },
  { id: 359,
    city: 'Greensboro',
    state: 'NC',
    value: 'Greensboro, NC' },
  { id: 360,
    city: 'Greenville',
    state: 'NC',
    value: 'Greenville, NC' },
  { id: 361,
    city: 'Greenville',
    state: 'SC',
    value: 'Greenville, SC' },
  { id: 362,
    city: 'Greenwood',
    state: 'IN',
    value: 'Greenwood, IN' },
  { id: 363, city: 'Gresham', state: 'OR', value: 'Gresham, OR' },
  { id: 364,
    city: 'Grove City',
    state: 'OH',
    value: 'Grove City, OH' },
  { id: 365, city: 'Gulfport', state: 'MS', value: 'Gulfport, MS' },
  { id: 366,
    city: 'Hackensack',
    state: 'NJ',
    value: 'Hackensack, NJ' },
  { id: 367,
    city: 'Hagerstown',
    state: 'MD',
    value: 'Hagerstown, MD' },
  { id: 368,
    city: 'Hallandale Beach',
    state: 'FL',
    value: 'Hallandale Beach, FL' },
  { id: 369,
    city: 'Haltom City',
    state: 'TX',
    value: 'Haltom City, TX' },
  { id: 370, city: 'Hamilton', state: 'OH', value: 'Hamilton, OH' },
  { id: 371, city: 'Hammond', state: 'IN', value: 'Hammond, IN' },
  { id: 372, city: 'Hampton', state: 'VA', value: 'Hampton, VA' },
  { id: 373, city: 'Hanford', state: 'CA', value: 'Hanford, CA' },
  { id: 374,
    city: 'Hanover Park',
    state: 'IL',
    value: 'Hanover Park, IL' },
  { id: 375,
    city: 'Harlingen',
    state: 'TX',
    value: 'Harlingen, TX' },
  { id: 376,
    city: 'Harrisburg',
    state: 'PA',
    value: 'Harrisburg, PA' },
  { id: 377,
    city: 'Harrisonburg',
    state: 'VA',
    value: 'Harrisonburg, VA' },
  { id: 378, city: 'Hartford', state: 'CT', value: 'Hartford, CT' },
  { id: 379,
    city: 'Hattiesburg',
    state: 'MS',
    value: 'Hattiesburg, MS' },
  { id: 380,
    city: 'Haverhill',
    state: 'MA',
    value: 'Haverhill, MA' },
  { id: 381,
    city: 'Hawthorne',
    state: 'CA',
    value: 'Hawthorne, CA' },
  { id: 382, city: 'Hayward', state: 'CA', value: 'Hayward, CA' },
  { id: 383, city: 'Hemet', state: 'CA', value: 'Hemet, CA' },
  { id: 384,
    city: 'Hempstead',
    state: 'NY',
    value: 'Hempstead, NY' },
  { id: 385,
    city: 'Henderson',
    state: 'NV',
    value: 'Henderson, NV' },
  { id: 386,
    city: 'Hendersonville',
    state: 'TN',
    value: 'Hendersonville, TN' },
  { id: 387, city: 'Hesperia', state: 'CA', value: 'Hesperia, CA' },
  { id: 388, city: 'Hialeah', state: 'FL', value: 'Hialeah, FL' },
  { id: 389, city: 'Hickory', state: 'NC', value: 'Hickory, NC' },
  { id: 390,
    city: 'High Point',
    state: 'NC',
    value: 'High Point, NC' },
  { id: 391, city: 'Highland', state: 'CA', value: 'Highland, CA' },
  { id: 392,
    city: 'Hillsboro',
    state: 'OR',
    value: 'Hillsboro, OR' },
  { id: 393,
    city: 'Hilton Head Island',
    state: 'SC',
    value: 'Hilton Head Island, SC' },
  { id: 394, city: 'Hoboken', state: 'NJ', value: 'Hoboken, NJ' },
  { id: 395,
    city: 'Hoffman Estates',
    state: 'IL',
    value: 'Hoffman Estates, IL' },
  { id: 396,
    city: 'Hollywood',
    state: 'FL',
    value: 'Hollywood, FL' },
  { id: 397, city: 'Holyoke', state: 'MA', value: 'Holyoke, MA' },
  { id: 398,
    city: 'Homestead',
    state: 'FL',
    value: 'Homestead, FL' },
  { id: 399, city: 'Honolulu', state: 'HI', value: 'Honolulu, HI' },
  { id: 400, city: 'Hoover', state: 'AL', value: 'Hoover, AL' },
  { id: 401, city: 'Houston', state: 'TX', value: 'Houston, TX' },
  { id: 402,
    city: 'Huber Heights',
    state: 'OH',
    value: 'Huber Heights, OH' },
  { id: 403,
    city: 'Huntersville',
    state: 'NC',
    value: 'Huntersville, NC' },
  { id: 404,
    city: 'Huntington',
    state: 'WV',
    value: 'Huntington, WV' },
  { id: 405,
    city: 'Huntington Beach',
    state: 'CA',
    value: 'Huntington Beach, CA' },
  { id: 406,
    city: 'Huntington Park',
    state: 'CA',
    value: 'Huntington Park, CA' },
  { id: 407,
    city: 'Huntsville',
    state: 'AL',
    value: 'Huntsville, AL' },
  { id: 408,
    city: 'Huntsville',
    state: 'TX',
    value: 'Huntsville, TX' },
  { id: 409, city: 'Hurst', state: 'TX', value: 'Hurst, TX' },
  { id: 410,
    city: 'Hutchinson',
    state: 'KS',
    value: 'Hutchinson, KS' },
  { id: 411,
    city: 'Idaho Falls',
    state: 'ID',
    value: 'Idaho Falls, ID' },
  { id: 412,
    city: 'Independence',
    state: 'MO',
    value: 'Independence, MO' },
  { id: 413,
    city: 'Indianapolis',
    state: 'IN',
    value: 'Indianapolis, IN' },
  { id: 414, city: 'Indio', state: 'CA', value: 'Indio, CA' },
  { id: 415,
    city: 'Inglewood',
    state: 'CA',
    value: 'Inglewood, CA' },
  { id: 416,
    city: 'Iowa City',
    state: 'IA',
    value: 'Iowa City, IA' },
  { id: 417, city: 'Irvine', state: 'CA', value: 'Irvine, CA' },
  { id: 418, city: 'Irving', state: 'TX', value: 'Irving, TX' },
  { id: 419, city: 'Jackson', state: 'MS', value: 'Jackson, MS' },
  { id: 420, city: 'Jackson', state: 'TN', value: 'Jackson, TN' },
  { id: 421,
    city: 'Jacksonville',
    state: 'FL',
    value: 'Jacksonville, FL' },
  { id: 422,
    city: 'Jacksonville',
    state: 'NC',
    value: 'Jacksonville, NC' },
  { id: 423,
    city: 'Janesville',
    state: 'WI',
    value: 'Janesville, WI' },
  { id: 424,
    city: 'Jefferson City',
    state: 'MO',
    value: 'Jefferson City, MO' },
  { id: 425,
    city: 'Jeffersonville',
    state: 'IN',
    value: 'Jeffersonville, IN' },
  { id: 426,
    city: 'Jersey City',
    state: 'NJ',
    value: 'Jersey City, NJ' },
  { id: 427,
    city: 'Johns Creek',
    state: 'GA',
    value: 'Johns Creek, GA' },
  { id: 428,
    city: 'Johnson City',
    state: 'TN',
    value: 'Johnson City, TN' },
  { id: 429, city: 'Joliet', state: 'IL', value: 'Joliet, IL' },
  { id: 430,
    city: 'Jonesboro',
    state: 'AR',
    value: 'Jonesboro, AR' },
  { id: 431, city: 'Joplin', state: 'MO', value: 'Joplin, MO' },
  { id: 432, city: 'Jupiter', state: 'FL', value: 'Jupiter, FL' },
  { id: 433,
    city: 'Jurupa Valley',
    state: 'CA',
    value: 'Jurupa Valley, CA' },
  { id: 434,
    city: 'Kalamazoo',
    state: 'MI',
    value: 'Kalamazoo, MI' },
  { id: 435,
    city: 'Kannapolis',
    state: 'NC',
    value: 'Kannapolis, NC' },
  { id: 436,
    city: 'Kansas City',
    state: 'MO',
    value: 'Kansas City, MO' },
  { id: 437,
    city: 'Kansas City',
    state: 'KS',
    value: 'Kansas City, KS' },
  { id: 438, city: 'Kearny', state: 'NJ', value: 'Kearny, NJ' },
  { id: 439, city: 'Keizer', state: 'OR', value: 'Keizer, OR' },
  { id: 440, city: 'Keller', state: 'TX', value: 'Keller, TX' },
  { id: 441, city: 'Kenner', state: 'LA', value: 'Kenner, LA' },
  { id: 442,
    city: 'Kennewick',
    state: 'WA',
    value: 'Kennewick, WA' },
  { id: 443, city: 'Kenosha', state: 'WI', value: 'Kenosha, WI' },
  { id: 444, city: 'Kent', state: 'WA', value: 'Kent, WA' },
  { id: 445, city: 'Kentwood', state: 'MI', value: 'Kentwood, MI' },
  { id: 446,
    city: 'Kettering',
    state: 'OH',
    value: 'Kettering, OH' },
  { id: 447, city: 'Killeen', state: 'TX', value: 'Killeen, TX' },
  { id: 448,
    city: 'Kingsport',
    state: 'TN',
    value: 'Kingsport, TN' },
  { id: 449, city: 'Kirkland', state: 'WA', value: 'Kirkland, WA' },
  { id: 450,
    city: 'Kissimmee',
    state: 'FL',
    value: 'Kissimmee, FL' },
  { id: 451,
    city: 'Knoxville',
    state: 'TN',
    value: 'Knoxville, TN' },
  { id: 452, city: 'Kokomo', state: 'IN', value: 'Kokomo, IN' },
  { id: 453,
    city: 'La Crosse',
    state: 'WI',
    value: 'La Crosse, WI' },
  { id: 454, city: 'La Habra', state: 'CA', value: 'La Habra, CA' },
  { id: 455, city: 'La Mesa', state: 'CA', value: 'La Mesa, CA' },
  { id: 456,
    city: 'La Mirada',
    state: 'CA',
    value: 'La Mirada, CA' },
  { id: 457,
    city: 'La Puente',
    state: 'CA',
    value: 'La Puente, CA' },
  { id: 458,
    city: 'La Quinta',
    state: 'CA',
    value: 'La Quinta, CA' },
  { id: 459, city: 'Lacey', state: 'WA', value: 'Lacey, WA' },
  { id: 460,
    city: 'Lafayette',
    state: 'LA',
    value: 'Lafayette, LA' },
  { id: 461,
    city: 'Lafayette',
    state: 'IN',
    value: 'Lafayette, IN' },
  { id: 462,
    city: 'Laguna Niguel',
    state: 'CA',
    value: 'Laguna Niguel, CA' },
  { id: 463,
    city: 'Lake Charles',
    state: 'LA',
    value: 'Lake Charles, LA' },
  { id: 464,
    city: 'Lake Elsinore',
    state: 'CA',
    value: 'Lake Elsinore, CA' },
  { id: 465,
    city: 'Lake Forest',
    state: 'CA',
    value: 'Lake Forest, CA' },
  { id: 466,
    city: 'Lake Havasu City',
    state: 'AZ',
    value: 'Lake Havasu City, AZ' },
  { id: 467,
    city: 'Lake Oswego',
    state: 'OR',
    value: 'Lake Oswego, OR' },
  { id: 468, city: 'Lakeland', state: 'FL', value: 'Lakeland, FL' },
  { id: 469,
    city: 'Lakeville',
    state: 'MN',
    value: 'Lakeville, MN' },
  { id: 470, city: 'Lakewood', state: 'CO', value: 'Lakewood, CO' },
  { id: 471, city: 'Lakewood', state: 'CA', value: 'Lakewood, CA' },
  { id: 472, city: 'Lakewood', state: 'WA', value: 'Lakewood, WA' },
  { id: 473, city: 'Lakewood', state: 'OH', value: 'Lakewood, OH' },
  { id: 474,
    city: 'Lancaster',
    state: 'CA',
    value: 'Lancaster, CA' },
  { id: 475,
    city: 'Lancaster',
    state: 'PA',
    value: 'Lancaster, PA' },
  { id: 476,
    city: 'Lancaster',
    state: 'OH',
    value: 'Lancaster, OH' },
  { id: 477,
    city: 'Lancaster',
    state: 'TX',
    value: 'Lancaster, TX' },
  { id: 478, city: 'Lansing', state: 'MI', value: 'Lansing, MI' },
  { id: 479, city: 'Laredo', state: 'TX', value: 'Laredo, TX' },
  { id: 480, city: 'Largo', state: 'FL', value: 'Largo, FL' },
  { id: 481,
    city: 'Las Cruces',
    state: 'NM',
    value: 'Las Cruces, NM' },
  { id: 482,
    city: 'Las Vegas',
    state: 'NV',
    value: 'Las Vegas, NV' },
  { id: 483,
    city: 'Lauderhill',
    state: 'FL',
    value: 'Lauderhill, FL' },
  { id: 484, city: 'Lawrence', state: 'KS', value: 'Lawrence, KS' },
  { id: 485, city: 'Lawrence', state: 'MA', value: 'Lawrence, MA' },
  { id: 486, city: 'Lawrence', state: 'IN', value: 'Lawrence, IN' },
  { id: 487, city: 'Lawton', state: 'OK', value: 'Lawton, OK' },
  { id: 488, city: 'Layton', state: 'UT', value: 'Layton, UT' },
  { id: 489,
    city: 'League City',
    state: 'TX',
    value: 'League City, TX' },
  { id: 490,
    city: 'Lee\'s Summit',
    state: 'MO',
    value: 'Lee\'s Summit, MO' },
  { id: 491, city: 'Leesburg', state: 'VA', value: 'Leesburg, VA' },
  { id: 492, city: 'Lehi', state: 'UT', value: 'Lehi, UT' },
  { id: 493, city: 'Lenexa', state: 'KS', value: 'Lenexa, KS' },
  { id: 494,
    city: 'Leominster',
    state: 'MA',
    value: 'Leominster, MA' },
  { id: 495,
    city: 'Lewisville',
    state: 'TX',
    value: 'Lewisville, TX' },
  { id: 496,
    city: 'Lexington-Fayette',
    state: 'KY',
    value: 'Lexington-Fayette, KY' },
  { id: 497, city: 'Lima', state: 'OH', value: 'Lima, OH' },
  { id: 498, city: 'Lincoln', state: 'NE', value: 'Lincoln, NE' },
  { id: 499, city: 'Lincoln', state: 'CA', value: 'Lincoln, CA' },
  { id: 500,
    city: 'Lincoln Park',
    state: 'MI',
    value: 'Lincoln Park, MI' },
  { id: 501, city: 'Linden', state: 'NJ', value: 'Linden, NJ' },
  { id: 502,
    city: 'Little Rock',
    state: 'AR',
    value: 'Little Rock, AR' },
  { id: 503,
    city: 'Littleton',
    state: 'CO',
    value: 'Littleton, CO' },
  { id: 504,
    city: 'Livermore',
    state: 'CA',
    value: 'Livermore, CA' },
  { id: 505, city: 'Livonia', state: 'MI', value: 'Livonia, MI' },
  { id: 506, city: 'Lodi', state: 'CA', value: 'Lodi, CA' },
  { id: 507, city: 'Logan', state: 'UT', value: 'Logan, UT' },
  { id: 508, city: 'Lombard', state: 'IL', value: 'Lombard, IL' },
  { id: 509, city: 'Lompoc', state: 'CA', value: 'Lompoc, CA' },
  { id: 510,
    city: 'Long Beach',
    state: 'CA',
    value: 'Long Beach, CA' },
  { id: 511, city: 'Longmont', state: 'CO', value: 'Longmont, CO' },
  { id: 512, city: 'Longview', state: 'TX', value: 'Longview, TX' },
  { id: 513, city: 'Lorain', state: 'OH', value: 'Lorain, OH' },
  { id: 514,
    city: 'Los Angeles',
    state: 'CA',
    value: 'Los Angeles, CA' },
  { id: 515,
    city: 'Louisville/Jefferson County',
    state: 'KY',
    value: 'Louisville/Jefferson County, KY' },
  { id: 516, city: 'Loveland', state: 'CO', value: 'Loveland, CO' },
  { id: 517, city: 'Lowell', state: 'MA', value: 'Lowell, MA' },
  { id: 518, city: 'Lubbock', state: 'TX', value: 'Lubbock, TX' },
  { id: 519,
    city: 'Lynchburg',
    state: 'VA',
    value: 'Lynchburg, VA' },
  { id: 520, city: 'Lynn', state: 'MA', value: 'Lynn, MA' },
  { id: 521, city: 'Lynwood', state: 'CA', value: 'Lynwood, CA' },
  { id: 522, city: 'Macon', state: 'GA', value: 'Macon, GA' },
  { id: 523, city: 'Madera', state: 'CA', value: 'Madera, CA' },
  { id: 524, city: 'Madison', state: 'WI', value: 'Madison, WI' },
  { id: 525, city: 'Madison', state: 'AL', value: 'Madison, AL' },
  { id: 526, city: 'Malden', state: 'MA', value: 'Malden, MA' },
  { id: 527, city: 'Manassas', state: 'VA', value: 'Manassas, VA' },
  { id: 528,
    city: 'Manchester',
    state: 'NH',
    value: 'Manchester, NH' },
  { id: 529,
    city: 'Manhattan',
    state: 'KS',
    value: 'Manhattan, KS' },
  { id: 530, city: 'Mankato', state: 'MN', value: 'Mankato, MN' },
  { id: 531,
    city: 'Mansfield',
    state: 'TX',
    value: 'Mansfield, TX' },
  { id: 532,
    city: 'Mansfield',
    state: 'OH',
    value: 'Mansfield, OH' },
  { id: 533, city: 'Manteca', state: 'CA', value: 'Manteca, CA' },
  { id: 534,
    city: 'Maple Grove',
    state: 'MN',
    value: 'Maple Grove, MN' },
  { id: 535,
    city: 'Maplewood',
    state: 'MN',
    value: 'Maplewood, MN' },
  { id: 536, city: 'Marana', state: 'AZ', value: 'Marana, AZ' },
  { id: 537, city: 'Margate', state: 'FL', value: 'Margate, FL' },
  { id: 538, city: 'Maricopa', state: 'AZ', value: 'Maricopa, AZ' },
  { id: 539, city: 'Marietta', state: 'GA', value: 'Marietta, GA' },
  { id: 540,
    city: 'Marlborough',
    state: 'MA',
    value: 'Marlborough, MA' },
  { id: 541, city: 'Martinez', state: 'CA', value: 'Martinez, CA' },
  { id: 542,
    city: 'Marysville',
    state: 'WA',
    value: 'Marysville, WA' },
  { id: 543, city: 'McAllen', state: 'TX', value: 'McAllen, TX' },
  { id: 544, city: 'McKinney', state: 'TX', value: 'McKinney, TX' },
  { id: 545, city: 'Medford', state: 'OR', value: 'Medford, OR' },
  { id: 546, city: 'Medford', state: 'MA', value: 'Medford, MA' },
  { id: 547,
    city: 'Melbourne',
    state: 'FL',
    value: 'Melbourne, FL' },
  { id: 548, city: 'Memphis', state: 'TN', value: 'Memphis, TN' },
  { id: 549, city: 'Menifee', state: 'CA', value: 'Menifee, CA' },
  { id: 550, city: 'Mentor', state: 'OH', value: 'Mentor, OH' },
  { id: 551, city: 'Merced', state: 'CA', value: 'Merced, CA' },
  { id: 552, city: 'Meriden', state: 'CT', value: 'Meriden, CT' },
  { id: 553, city: 'Meridian', state: 'ID', value: 'Meridian, ID' },
  { id: 554, city: 'Meridian', state: 'MS', value: 'Meridian, MS' },
  { id: 555, city: 'Mesa', state: 'AZ', value: 'Mesa, AZ' },
  { id: 556, city: 'Mesquite', state: 'TX', value: 'Mesquite, TX' },
  { id: 557, city: 'Methuen', state: 'MA', value: 'Methuen, MA' },
  { id: 558, city: 'Miami', state: 'FL', value: 'Miami, FL' },
  { id: 559,
    city: 'Miami Beach',
    state: 'FL',
    value: 'Miami Beach, FL' },
  { id: 560,
    city: 'Miami Gardens',
    state: 'FL',
    value: 'Miami Gardens, FL' },
  { id: 561,
    city: 'Middletown',
    state: 'OH',
    value: 'Middletown, OH' },
  { id: 562,
    city: 'Middletown',
    state: 'CT',
    value: 'Middletown, CT' },
  { id: 563, city: 'Midland', state: 'TX', value: 'Midland, TX' },
  { id: 564, city: 'Midland', state: 'MI', value: 'Midland, MI' },
  { id: 565,
    city: 'Midwest City',
    state: 'OK',
    value: 'Midwest City, OK' },
  { id: 566, city: 'Milford', state: 'CT', value: 'Milford, CT' },
  { id: 567, city: 'Milpitas', state: 'CA', value: 'Milpitas, CA' },
  { id: 568,
    city: 'Milwaukee',
    state: 'WI',
    value: 'Milwaukee, WI' },
  { id: 569,
    city: 'Minneapolis',
    state: 'MN',
    value: 'Minneapolis, MN' },
  { id: 570,
    city: 'Minnetonka',
    state: 'MN',
    value: 'Minnetonka, MN' },
  { id: 571, city: 'Minot', state: 'ND', value: 'Minot, ND' },
  { id: 572, city: 'Miramar', state: 'FL', value: 'Miramar, FL' },
  { id: 573,
    city: 'Mishawaka',
    state: 'IN',
    value: 'Mishawaka, IN' },
  { id: 574, city: 'Mission', state: 'TX', value: 'Mission, TX' },
  { id: 575,
    city: 'Mission Viejo',
    state: 'CA',
    value: 'Mission Viejo, CA' },
  { id: 576, city: 'Missoula', state: 'MT', value: 'Missoula, MT' },
  { id: 577,
    city: 'Missouri City',
    state: 'TX',
    value: 'Missouri City, TX' },
  { id: 578, city: 'Mobile', state: 'AL', value: 'Mobile, AL' },
  { id: 579, city: 'Modesto', state: 'CA', value: 'Modesto, CA' },
  { id: 580, city: 'Moline', state: 'IL', value: 'Moline, IL' },
  { id: 581, city: 'Monroe', state: 'LA', value: 'Monroe, LA' },
  { id: 582, city: 'Monrovia', state: 'CA', value: 'Monrovia, CA' },
  { id: 583,
    city: 'Montclair',
    state: 'CA',
    value: 'Montclair, CA' },
  { id: 584,
    city: 'Montebello',
    state: 'CA',
    value: 'Montebello, CA' },
  { id: 585,
    city: 'Monterey Park',
    state: 'CA',
    value: 'Monterey Park, CA' },
  { id: 586,
    city: 'Montgomery',
    state: 'AL',
    value: 'Montgomery, AL' },
  { id: 587, city: 'Moore', state: 'OK', value: 'Moore, OK' },
  { id: 588, city: 'Moorhead', state: 'MN', value: 'Moorhead, MN' },
  { id: 589,
    city: 'Moreno Valley',
    state: 'CA',
    value: 'Moreno Valley, CA' },
  { id: 590,
    city: 'Morgan Hill',
    state: 'CA',
    value: 'Morgan Hill, CA' },
  { id: 591,
    city: 'Mount Pleasant',
    state: 'SC',
    value: 'Mount Pleasant, SC' },
  { id: 592,
    city: 'Mount Prospect',
    state: 'IL',
    value: 'Mount Prospect, IL' },
  { id: 593,
    city: 'Mount Vernon',
    state: 'NY',
    value: 'Mount Vernon, NY' },
  { id: 594,
    city: 'Mountain View',
    state: 'CA',
    value: 'Mountain View, CA' },
  { id: 595, city: 'Muncie', state: 'IN', value: 'Muncie, IN' },
  { id: 596,
    city: 'Murfreesboro',
    state: 'TN',
    value: 'Murfreesboro, TN' },
  { id: 597, city: 'Murray', state: 'UT', value: 'Murray, UT' },
  { id: 598, city: 'Murrieta', state: 'CA', value: 'Murrieta, CA' },
  { id: 599, city: 'Muskegon', state: 'MI', value: 'Muskegon, MI' },
  { id: 600, city: 'Muskogee', state: 'OK', value: 'Muskogee, OK' },
  { id: 601, city: 'Nampa', state: 'ID', value: 'Nampa, ID' },
  { id: 602, city: 'Napa', state: 'CA', value: 'Napa, CA' },
  { id: 603,
    city: 'Naperville',
    state: 'IL',
    value: 'Naperville, IL' },
  { id: 604, city: 'Nashua', state: 'NH', value: 'Nashua, NH' },
  { id: 605,
    city: 'Nashville-Davidson',
    state: 'TN',
    value: 'Nashville-Davidson, TN' },
  { id: 606,
    city: 'National City',
    state: 'CA',
    value: 'National City, CA' },
  { id: 607,
    city: 'New Bedford',
    state: 'MA',
    value: 'New Bedford, MA' },
  { id: 608,
    city: 'New Berlin',
    state: 'WI',
    value: 'New Berlin, WI' },
  { id: 609,
    city: 'New Braunfels',
    state: 'TX',
    value: 'New Braunfels, TX' },
  { id: 610,
    city: 'New Britain',
    state: 'CT',
    value: 'New Britain, CT' },
  { id: 611,
    city: 'New Brunswick',
    state: 'NJ',
    value: 'New Brunswick, NJ' },
  { id: 612,
    city: 'New Haven',
    state: 'CT',
    value: 'New Haven, CT' },
  { id: 613,
    city: 'New Orleans',
    state: 'LA',
    value: 'New Orleans, LA' },
  { id: 614,
    city: 'New Rochelle',
    state: 'NY',
    value: 'New Rochelle, NY' },
  { id: 615, city: 'New York', state: 'NY', value: 'New York, NY' },
  { id: 616, city: 'Newark', state: 'NJ', value: 'Newark, NJ' },
  { id: 617, city: 'Newark', state: 'OH', value: 'Newark, OH' },
  { id: 618, city: 'Newark', state: 'CA', value: 'Newark, CA' },
  { id: 619,
    city: 'Newport Beach',
    state: 'CA',
    value: 'Newport Beach, CA' },
  { id: 620,
    city: 'Newport News',
    state: 'VA',
    value: 'Newport News, VA' },
  { id: 621, city: 'Newton', state: 'MA', value: 'Newton, MA' },
  { id: 622,
    city: 'Niagara Falls',
    state: 'NY',
    value: 'Niagara Falls, NY' },
  { id: 623,
    city: 'Noblesville',
    state: 'IN',
    value: 'Noblesville, IN' },
  { id: 624, city: 'Norfolk', state: 'VA', value: 'Norfolk, VA' },
  { id: 625, city: 'Normal', state: 'IL', value: 'Normal, IL' },
  { id: 626, city: 'Norman', state: 'OK', value: 'Norman, OK' },
  { id: 627,
    city: 'North Charleston',
    state: 'SC',
    value: 'North Charleston, SC' },
  { id: 628,
    city: 'North Las Vegas',
    state: 'NV',
    value: 'North Las Vegas, NV' },
  { id: 629,
    city: 'North Lauderdale',
    state: 'FL',
    value: 'North Lauderdale, FL' },
  { id: 630,
    city: 'North Little Rock',
    state: 'AR',
    value: 'North Little Rock, AR' },
  { id: 631,
    city: 'North Miami',
    state: 'FL',
    value: 'North Miami, FL' },
  { id: 632,
    city: 'North Miami Beach',
    state: 'FL',
    value: 'North Miami Beach, FL' },
  { id: 633,
    city: 'North Port',
    state: 'FL',
    value: 'North Port, FL' },
  { id: 634,
    city: 'North Richland Hills',
    state: 'TX',
    value: 'North Richland Hills, TX' },
  { id: 635,
    city: 'Northglenn',
    state: 'CO',
    value: 'Northglenn, CO' },
  { id: 636, city: 'Norwalk', state: 'CA', value: 'Norwalk, CA' },
  { id: 637, city: 'Norwalk', state: 'CT', value: 'Norwalk, CT' },
  { id: 638, city: 'Norwich', state: 'CT', value: 'Norwich, CT' },
  { id: 639, city: 'Novato', state: 'CA', value: 'Novato, CA' },
  { id: 640, city: 'Novi', state: 'MI', value: 'Novi, MI' },
  { id: 641,
    city: 'O\'Fallon',
    state: 'MO',
    value: 'O\'Fallon, MO' },
  { id: 642, city: 'Oak Lawn', state: 'IL', value: 'Oak Lawn, IL' },
  { id: 643, city: 'Oak Park', state: 'IL', value: 'Oak Park, IL' },
  { id: 644, city: 'Oakland', state: 'CA', value: 'Oakland, CA' },
  { id: 645,
    city: 'Oakland Park',
    state: 'FL',
    value: 'Oakland Park, FL' },
  { id: 646, city: 'Oakley', state: 'CA', value: 'Oakley, CA' },
  { id: 647, city: 'Ocala', state: 'FL', value: 'Ocala, FL' },
  { id: 648,
    city: 'Oceanside',
    state: 'CA',
    value: 'Oceanside, CA' },
  { id: 649, city: 'Ocoee', state: 'FL', value: 'Ocoee, FL' },
  { id: 650, city: 'Odessa', state: 'TX', value: 'Odessa, TX' },
  { id: 651, city: 'Ogden', state: 'UT', value: 'Ogden, UT' },
  { id: 652,
    city: 'Oklahoma City',
    state: 'OK',
    value: 'Oklahoma City, OK' },
  { id: 653, city: 'Olathe', state: 'KS', value: 'Olathe, KS' },
  { id: 654, city: 'Olympia', state: 'WA', value: 'Olympia, WA' },
  { id: 655, city: 'Omaha', state: 'NE', value: 'Omaha, NE' },
  { id: 656, city: 'Ontario', state: 'CA', value: 'Ontario, CA' },
  { id: 657, city: 'Orange', state: 'CA', value: 'Orange, CA' },
  { id: 658, city: 'Orem', state: 'UT', value: 'Orem, UT' },
  { id: 659,
    city: 'Orland Park',
    state: 'IL',
    value: 'Orland Park, IL' },
  { id: 660, city: 'Orlando', state: 'FL', value: 'Orlando, FL' },
  { id: 661,
    city: 'Ormond Beach',
    state: 'FL',
    value: 'Ormond Beach, FL' },
  { id: 662,
    city: 'Oro Valley',
    state: 'AZ',
    value: 'Oro Valley, AZ' },
  { id: 663, city: 'Oshkosh', state: 'WI', value: 'Oshkosh, WI' },
  { id: 664,
    city: 'Overland Park',
    state: 'KS',
    value: 'Overland Park, KS' },
  { id: 665,
    city: 'Owensboro',
    state: 'KY',
    value: 'Owensboro, KY' },
  { id: 666, city: 'Oxnard', state: 'CA', value: 'Oxnard, CA' },
  { id: 667, city: 'Pacifica', state: 'CA', value: 'Pacifica, CA' },
  { id: 668, city: 'Palatine', state: 'IL', value: 'Palatine, IL' },
  { id: 669, city: 'Palm Bay', state: 'FL', value: 'Palm Bay, FL' },
  { id: 670,
    city: 'Palm Beach Gardens',
    state: 'FL',
    value: 'Palm Beach Gardens, FL' },
  { id: 671,
    city: 'Palm Coast',
    state: 'FL',
    value: 'Palm Coast, FL' },
  { id: 672,
    city: 'Palm Desert',
    state: 'CA',
    value: 'Palm Desert, CA' },
  { id: 673,
    city: 'Palm Springs',
    state: 'CA',
    value: 'Palm Springs, CA' },
  { id: 674, city: 'Palmdale', state: 'CA', value: 'Palmdale, CA' },
  { id: 675,
    city: 'Palo Alto',
    state: 'CA',
    value: 'Palo Alto, CA' },
  { id: 676,
    city: 'Panama City',
    state: 'FL',
    value: 'Panama City, FL' },
  { id: 677,
    city: 'Paramount',
    state: 'CA',
    value: 'Paramount, CA' },
  { id: 678,
    city: 'Park Ridge',
    state: 'IL',
    value: 'Park Ridge, IL' },
  { id: 679, city: 'Parker', state: 'CO', value: 'Parker, CO' },
  { id: 680, city: 'Parma', state: 'OH', value: 'Parma, OH' },
  { id: 681, city: 'Pasadena', state: 'TX', value: 'Pasadena, TX' },
  { id: 682, city: 'Pasadena', state: 'CA', value: 'Pasadena, CA' },
  { id: 683, city: 'Pasco', state: 'WA', value: 'Pasco, WA' },
  { id: 684, city: 'Passaic', state: 'NJ', value: 'Passaic, NJ' },
  { id: 685, city: 'Paterson', state: 'NJ', value: 'Paterson, NJ' },
  { id: 686,
    city: 'Pawtucket',
    state: 'RI',
    value: 'Pawtucket, RI' },
  { id: 687, city: 'Peabody', state: 'MA', value: 'Peabody, MA' },
  { id: 688,
    city: 'Peachtree Corners',
    state: 'GA',
    value: 'Peachtree Corners, GA' },
  { id: 689, city: 'Pearland', state: 'TX', value: 'Pearland, TX' },
  { id: 690,
    city: 'Pembroke Pines',
    state: 'FL',
    value: 'Pembroke Pines, FL' },
  { id: 691,
    city: 'Pensacola',
    state: 'FL',
    value: 'Pensacola, FL' },
  { id: 692, city: 'Peoria', state: 'AZ', value: 'Peoria, AZ' },
  { id: 693, city: 'Peoria', state: 'IL', value: 'Peoria, IL' },
  { id: 694, city: 'Perris', state: 'CA', value: 'Perris, CA' },
  { id: 695,
    city: 'Perth Amboy',
    state: 'NJ',
    value: 'Perth Amboy, NJ' },
  { id: 696, city: 'Petaluma', state: 'CA', value: 'Petaluma, CA' },
  { id: 697,
    city: 'Pflugerville',
    state: 'TX',
    value: 'Pflugerville, TX' },
  { id: 698, city: 'Pharr', state: 'TX', value: 'Pharr, TX' },
  { id: 699,
    city: 'Phenix City',
    state: 'AL',
    value: 'Phenix City, AL' },
  { id: 700,
    city: 'Philadelphia',
    state: 'PA',
    value: 'Philadelphia, PA' },
  { id: 701, city: 'Phoenix', state: 'AZ', value: 'Phoenix, AZ' },
  { id: 702,
    city: 'Pico Rivera',
    state: 'CA',
    value: 'Pico Rivera, CA' },
  { id: 703,
    city: 'Pine Bluff',
    state: 'AR',
    value: 'Pine Bluff, AR' },
  { id: 704,
    city: 'Pinellas Park',
    state: 'FL',
    value: 'Pinellas Park, FL' },
  { id: 705,
    city: 'Pittsburg',
    state: 'CA',
    value: 'Pittsburg, CA' },
  { id: 706,
    city: 'Pittsburgh',
    state: 'PA',
    value: 'Pittsburgh, PA' },
  { id: 707,
    city: 'Pittsfield',
    state: 'MA',
    value: 'Pittsfield, MA' },
  { id: 708,
    city: 'Placentia',
    state: 'CA',
    value: 'Placentia, CA' },
  { id: 709,
    city: 'Plainfield',
    state: 'NJ',
    value: 'Plainfield, NJ' },
  { id: 710,
    city: 'Plainfield',
    state: 'IL',
    value: 'Plainfield, IL' },
  { id: 711, city: 'Plano', state: 'TX', value: 'Plano, TX' },
  { id: 712,
    city: 'Plantation',
    state: 'FL',
    value: 'Plantation, FL' },
  { id: 713,
    city: 'Pleasanton',
    state: 'CA',
    value: 'Pleasanton, CA' },
  { id: 714, city: 'Plymouth', state: 'MN', value: 'Plymouth, MN' },
  { id: 715,
    city: 'Pocatello',
    state: 'ID',
    value: 'Pocatello, ID' },
  { id: 716, city: 'Pomona', state: 'CA', value: 'Pomona, CA' },
  { id: 717,
    city: 'Pompano Beach',
    state: 'FL',
    value: 'Pompano Beach, FL' },
  { id: 718, city: 'Pontiac', state: 'MI', value: 'Pontiac, MI' },
  { id: 719,
    city: 'Port Arthur',
    state: 'TX',
    value: 'Port Arthur, TX' },
  { id: 720,
    city: 'Port Orange',
    state: 'FL',
    value: 'Port Orange, FL' },
  { id: 721,
    city: 'Port St. Lucie',
    state: 'FL',
    value: 'Port St. Lucie, FL' },
  { id: 722, city: 'Portage', state: 'MI', value: 'Portage, MI' },
  { id: 723,
    city: 'Porterville',
    state: 'CA',
    value: 'Porterville, CA' },
  { id: 724, city: 'Portland', state: 'OR', value: 'Portland, OR' },
  { id: 725, city: 'Portland', state: 'ME', value: 'Portland, ME' },
  { id: 726,
    city: 'Portsmouth',
    state: 'VA',
    value: 'Portsmouth, VA' },
  { id: 727, city: 'Poway', state: 'CA', value: 'Poway, CA' },
  { id: 728, city: 'Prescott', state: 'AZ', value: 'Prescott, AZ' },
  { id: 729,
    city: 'Prescott Valley',
    state: 'AZ',
    value: 'Prescott Valley, AZ' },
  { id: 730,
    city: 'Providence',
    state: 'RI',
    value: 'Providence, RI' },
  { id: 731, city: 'Provo', state: 'UT', value: 'Provo, UT' },
  { id: 732, city: 'Pueblo', state: 'CO', value: 'Pueblo, CO' },
  { id: 733, city: 'Puyallup', state: 'WA', value: 'Puyallup, WA' },
  { id: 734, city: 'Quincy', state: 'MA', value: 'Quincy, MA' },
  { id: 735, city: 'Quincy', state: 'IL', value: 'Quincy, IL' },
  { id: 736, city: 'Racine', state: 'WI', value: 'Racine, WI' },
  { id: 737, city: 'Raleigh', state: 'NC', value: 'Raleigh, NC' },
  { id: 738,
    city: 'Rancho Cordova',
    state: 'CA',
    value: 'Rancho Cordova, CA' },
  { id: 739,
    city: 'Rancho Cucamonga',
    state: 'CA',
    value: 'Rancho Cucamonga, CA' },
  { id: 740,
    city: 'Rancho Palos Verdes',
    state: 'CA',
    value: 'Rancho Palos Verdes, CA' },
  { id: 741,
    city: 'Rancho Santa Margarita',
    state: 'CA',
    value: 'Rancho Santa Margarita, CA' },
  { id: 742,
    city: 'Rapid City',
    state: 'SD',
    value: 'Rapid City, SD' },
  { id: 743, city: 'Reading', state: 'PA', value: 'Reading, PA' },
  { id: 744, city: 'Redding', state: 'CA', value: 'Redding, CA' },
  { id: 745, city: 'Redlands', state: 'CA', value: 'Redlands, CA' },
  { id: 746, city: 'Redmond', state: 'WA', value: 'Redmond, WA' },
  { id: 747,
    city: 'Redondo Beach',
    state: 'CA',
    value: 'Redondo Beach, CA' },
  { id: 748,
    city: 'Redwood City',
    state: 'CA',
    value: 'Redwood City, CA' },
  { id: 749, city: 'Reno', state: 'NV', value: 'Reno, NV' },
  { id: 750, city: 'Renton', state: 'WA', value: 'Renton, WA' },
  { id: 751, city: 'Revere', state: 'MA', value: 'Revere, MA' },
  { id: 752, city: 'Rialto', state: 'CA', value: 'Rialto, CA' },
  { id: 753,
    city: 'Richardson',
    state: 'TX',
    value: 'Richardson, TX' },
  { id: 754, city: 'Richland', state: 'WA', value: 'Richland, WA' },
  { id: 755, city: 'Richmond', state: 'VA', value: 'Richmond, VA' },
  { id: 756, city: 'Richmond', state: 'CA', value: 'Richmond, CA' },
  { id: 757,
    city: 'Rio Rancho',
    state: 'NM',
    value: 'Rio Rancho, NM' },
  { id: 758,
    city: 'Riverside',
    state: 'CA',
    value: 'Riverside, CA' },
  { id: 759, city: 'Riverton', state: 'UT', value: 'Riverton, UT' },
  { id: 760, city: 'Roanoke', state: 'VA', value: 'Roanoke, VA' },
  { id: 761,
    city: 'Rochester',
    state: 'NY',
    value: 'Rochester, NY' },
  { id: 762,
    city: 'Rochester',
    state: 'MN',
    value: 'Rochester, MN' },
  { id: 763,
    city: 'Rochester Hills',
    state: 'MI',
    value: 'Rochester Hills, MI' },
  { id: 764,
    city: 'Rock Hill',
    state: 'SC',
    value: 'Rock Hill, SC' },
  { id: 765,
    city: 'Rock Island',
    state: 'IL',
    value: 'Rock Island, IL' },
  { id: 766, city: 'Rockford', state: 'IL', value: 'Rockford, IL' },
  { id: 767, city: 'Rocklin', state: 'CA', value: 'Rocklin, CA' },
  { id: 768,
    city: 'Rockville',
    state: 'MD',
    value: 'Rockville, MD' },
  { id: 769, city: 'Rockwall', state: 'TX', value: 'Rockwall, TX' },
  { id: 770,
    city: 'Rocky Mount',
    state: 'NC',
    value: 'Rocky Mount, NC' },
  { id: 771, city: 'Rogers', state: 'AR', value: 'Rogers, AR' },
  { id: 772,
    city: 'Rohnert Park',
    state: 'CA',
    value: 'Rohnert Park, CA' },
  { id: 773,
    city: 'Romeoville',
    state: 'IL',
    value: 'Romeoville, IL' },
  { id: 774, city: 'Rosemead', state: 'CA', value: 'Rosemead, CA' },
  { id: 775,
    city: 'Roseville',
    state: 'CA',
    value: 'Roseville, CA' },
  { id: 776,
    city: 'Roseville',
    state: 'MI',
    value: 'Roseville, MI' },
  { id: 777, city: 'Roswell', state: 'GA', value: 'Roswell, GA' },
  { id: 778, city: 'Roswell', state: 'NM', value: 'Roswell, NM' },
  { id: 779,
    city: 'Round Rock',
    state: 'TX',
    value: 'Round Rock, TX' },
  { id: 780, city: 'Rowlett', state: 'TX', value: 'Rowlett, TX' },
  { id: 781, city: 'Roy', state: 'UT', value: 'Roy, UT' },
  { id: 782,
    city: 'Royal Oak',
    state: 'MI',
    value: 'Royal Oak, MI' },
  { id: 783,
    city: 'Sacramento',
    state: 'CA',
    value: 'Sacramento, CA' },
  { id: 784, city: 'Saginaw', state: 'MI', value: 'Saginaw, MI' },
  { id: 785, city: 'Salem', state: 'OR', value: 'Salem, OR' },
  { id: 786, city: 'Salem', state: 'MA', value: 'Salem, MA' },
  { id: 787, city: 'Salina', state: 'KS', value: 'Salina, KS' },
  { id: 788, city: 'Salinas', state: 'CA', value: 'Salinas, CA' },
  { id: 789,
    city: 'Salt Lake City',
    state: 'UT',
    value: 'Salt Lake City, UT' },
  { id: 790,
    city: 'Sammamish',
    state: 'WA',
    value: 'Sammamish, WA' },
  { id: 791,
    city: 'San Angelo',
    state: 'TX',
    value: 'San Angelo, TX' },
  { id: 792,
    city: 'San Antonio',
    state: 'TX',
    value: 'San Antonio, TX' },
  { id: 793,
    city: 'San Bernardino',
    state: 'CA',
    value: 'San Bernardino, CA' },
  { id: 794,
    city: 'San Bruno',
    state: 'CA',
    value: 'San Bruno, CA' },
  { id: 795,
    city: 'San Buenaventura (Ventura)',
    state: 'CA',
    value: 'San Buenaventura (Ventura), CA' },
  { id: 796,
    city: 'San Clemente',
    state: 'CA',
    value: 'San Clemente, CA' },
  { id: 797,
    city: 'San Diego',
    state: 'CA',
    value: 'San Diego, CA' },
  { id: 798,
    city: 'San Francisco',
    state: 'CA',
    value: 'San Francisco, CA' },
  { id: 799,
    city: 'San Gabriel',
    state: 'CA',
    value: 'San Gabriel, CA' },
  { id: 800,
    city: 'San Jacinto',
    state: 'CA',
    value: 'San Jacinto, CA' },
  { id: 801, city: 'San Jose', state: 'CA', value: 'San Jose, CA' },
  { id: 802,
    city: 'San Leandro',
    state: 'CA',
    value: 'San Leandro, CA' },
  { id: 803,
    city: 'San Luis Obispo',
    state: 'CA',
    value: 'San Luis Obispo, CA' },
  { id: 804,
    city: 'San Marcos',
    state: 'CA',
    value: 'San Marcos, CA' },
  { id: 805,
    city: 'San Marcos',
    state: 'TX',
    value: 'San Marcos, TX' },
  { id: 806,
    city: 'San Mateo',
    state: 'CA',
    value: 'San Mateo, CA' },
  { id: 807,
    city: 'San Rafael',
    state: 'CA',
    value: 'San Rafael, CA' },
  { id: 808,
    city: 'San Ramon',
    state: 'CA',
    value: 'San Ramon, CA' },
  { id: 809, city: 'Sandy', state: 'UT', value: 'Sandy, UT' },
  { id: 810,
    city: 'Sandy Springs',
    state: 'GA',
    value: 'Sandy Springs, GA' },
  { id: 811, city: 'Sanford', state: 'FL', value: 'Sanford, FL' },
  { id: 812,
    city: 'Santa Ana',
    state: 'CA',
    value: 'Santa Ana, CA' },
  { id: 813,
    city: 'Santa Barbara',
    state: 'CA',
    value: 'Santa Barbara, CA' },
  { id: 814,
    city: 'Santa Clara',
    state: 'CA',
    value: 'Santa Clara, CA' },
  { id: 815,
    city: 'Santa Clarita',
    state: 'CA',
    value: 'Santa Clarita, CA' },
  { id: 816,
    city: 'Santa Cruz',
    state: 'CA',
    value: 'Santa Cruz, CA' },
  { id: 817, city: 'Santa Fe', state: 'NM', value: 'Santa Fe, NM' },
  { id: 818,
    city: 'Santa Maria',
    state: 'CA',
    value: 'Santa Maria, CA' },
  { id: 819,
    city: 'Santa Monica',
    state: 'CA',
    value: 'Santa Monica, CA' },
  { id: 820,
    city: 'Santa Rosa',
    state: 'CA',
    value: 'Santa Rosa, CA' },
  { id: 821, city: 'Santee', state: 'CA', value: 'Santee, CA' },
  { id: 822, city: 'Sarasota', state: 'FL', value: 'Sarasota, FL' },
  { id: 823, city: 'Savannah', state: 'GA', value: 'Savannah, GA' },
  { id: 824,
    city: 'Sayreville',
    state: 'NJ',
    value: 'Sayreville, NJ' },
  { id: 825,
    city: 'Schaumburg',
    state: 'IL',
    value: 'Schaumburg, IL' },
  { id: 826,
    city: 'Schenectady',
    state: 'NY',
    value: 'Schenectady, NY' },
  { id: 827,
    city: 'Scottsdale',
    state: 'AZ',
    value: 'Scottsdale, AZ' },
  { id: 828, city: 'Scranton', state: 'PA', value: 'Scranton, PA' },
  { id: 829, city: 'Seattle', state: 'WA', value: 'Seattle, WA' },
  { id: 830, city: 'Shakopee', state: 'MN', value: 'Shakopee, MN' },
  { id: 831, city: 'Shawnee', state: 'KS', value: 'Shawnee, KS' },
  { id: 832,
    city: 'Sheboygan',
    state: 'WI',
    value: 'Sheboygan, WI' },
  { id: 833, city: 'Shelton', state: 'CT', value: 'Shelton, CT' },
  { id: 834, city: 'Sherman', state: 'TX', value: 'Sherman, TX' },
  { id: 835,
    city: 'Shoreline',
    state: 'WA',
    value: 'Shoreline, WA' },
  { id: 836,
    city: 'Shreveport',
    state: 'LA',
    value: 'Shreveport, LA' },
  { id: 837,
    city: 'Sierra Vista',
    state: 'AZ',
    value: 'Sierra Vista, AZ' },
  { id: 838,
    city: 'Simi Valley',
    state: 'CA',
    value: 'Simi Valley, CA' },
  { id: 839,
    city: 'Sioux City',
    state: 'IA',
    value: 'Sioux City, IA' },
  { id: 840,
    city: 'Sioux Falls',
    state: 'SD',
    value: 'Sioux Falls, SD' },
  { id: 841, city: 'Skokie', state: 'IL', value: 'Skokie, IL' },
  { id: 842, city: 'Smyrna', state: 'GA', value: 'Smyrna, GA' },
  { id: 843, city: 'Smyrna', state: 'TN', value: 'Smyrna, TN' },
  { id: 844,
    city: 'Somerville',
    state: 'MA',
    value: 'Somerville, MA' },
  { id: 845,
    city: 'South Bend',
    state: 'IN',
    value: 'South Bend, IN' },
  { id: 846,
    city: 'South Gate',
    state: 'CA',
    value: 'South Gate, CA' },
  { id: 847,
    city: 'South Jordan',
    state: 'UT',
    value: 'South Jordan, UT' },
  { id: 848,
    city: 'South San Francisco',
    state: 'CA',
    value: 'South San Francisco, CA' },
  { id: 849,
    city: 'Southaven',
    state: 'MS',
    value: 'Southaven, MS' },
  { id: 850,
    city: 'Southfield',
    state: 'MI',
    value: 'Southfield, MI' },
  { id: 851,
    city: 'Spanish Fork',
    state: 'UT',
    value: 'Spanish Fork, UT' },
  { id: 852, city: 'Sparks', state: 'NV', value: 'Sparks, NV' },
  { id: 853,
    city: 'Spartanburg',
    state: 'SC',
    value: 'Spartanburg, SC' },
  { id: 854, city: 'Spokane', state: 'WA', value: 'Spokane, WA' },
  { id: 855,
    city: 'Spokane Valley',
    state: 'WA',
    value: 'Spokane Valley, WA' },
  { id: 856,
    city: 'Springdale',
    state: 'AR',
    value: 'Springdale, AR' },
  { id: 857,
    city: 'Springfield',
    state: 'MO',
    value: 'Springfield, MO' },
  { id: 858,
    city: 'Springfield',
    state: 'MA',
    value: 'Springfield, MA' },
  { id: 859,
    city: 'Springfield',
    state: 'IL',
    value: 'Springfield, IL' },
  { id: 860,
    city: 'Springfield',
    state: 'OR',
    value: 'Springfield, OR' },
  { id: 861,
    city: 'Springfield',
    state: 'OH',
    value: 'Springfield, OH' },
  { id: 862,
    city: 'St. Charles',
    state: 'MO',
    value: 'St. Charles, MO' },
  { id: 863,
    city: 'St. Clair Shores',
    state: 'MI',
    value: 'St. Clair Shores, MI' },
  { id: 864,
    city: 'St. Cloud',
    state: 'MN',
    value: 'St. Cloud, MN' },
  { id: 865,
    city: 'St. Cloud',
    state: 'FL',
    value: 'St. Cloud, FL' },
  { id: 866,
    city: 'St. George',
    state: 'UT',
    value: 'St. George, UT' },
  { id: 867,
    city: 'St. Joseph',
    state: 'MO',
    value: 'St. Joseph, MO' },
  { id: 868,
    city: 'St. Louis',
    state: 'MO',
    value: 'St. Louis, MO' },
  { id: 869,
    city: 'St. Louis Park',
    state: 'MN',
    value: 'St. Louis Park, MN' },
  { id: 870, city: 'St. Paul', state: 'MN', value: 'St. Paul, MN' },
  { id: 871,
    city: 'St. Peters',
    state: 'MO',
    value: 'St. Peters, MO' },
  { id: 872,
    city: 'St. Petersburg',
    state: 'FL',
    value: 'St. Petersburg, FL' },
  { id: 873, city: 'Stamford', state: 'CT', value: 'Stamford, CT' },
  { id: 874, city: 'Stanton', state: 'CA', value: 'Stanton, CA' },
  { id: 875,
    city: 'State College',
    state: 'PA',
    value: 'State College, PA' },
  { id: 876,
    city: 'Sterling Heights',
    state: 'MI',
    value: 'Sterling Heights, MI' },
  { id: 877,
    city: 'Stillwater',
    state: 'OK',
    value: 'Stillwater, OK' },
  { id: 878, city: 'Stockton', state: 'CA', value: 'Stockton, CA' },
  { id: 879,
    city: 'Streamwood',
    state: 'IL',
    value: 'Streamwood, IL' },
  { id: 880,
    city: 'Strongsville',
    state: 'OH',
    value: 'Strongsville, OH' },
  { id: 881, city: 'Suffolk', state: 'VA', value: 'Suffolk, VA' },
  { id: 882,
    city: 'Sugar Land',
    state: 'TX',
    value: 'Sugar Land, TX' },
  { id: 883,
    city: 'Summerville',
    state: 'SC',
    value: 'Summerville, SC' },
  { id: 884, city: 'Sumter', state: 'SC', value: 'Sumter, SC' },
  { id: 885,
    city: 'Sunnyvale',
    state: 'CA',
    value: 'Sunnyvale, CA' },
  { id: 886, city: 'Sunrise', state: 'FL', value: 'Sunrise, FL' },
  { id: 887, city: 'Surprise', state: 'AZ', value: 'Surprise, AZ' },
  { id: 888, city: 'Syracuse', state: 'NY', value: 'Syracuse, NY' },
  { id: 889, city: 'Tacoma', state: 'WA', value: 'Tacoma, WA' },
  { id: 890,
    city: 'Tallahassee',
    state: 'FL',
    value: 'Tallahassee, FL' },
  { id: 891, city: 'Tamarac', state: 'FL', value: 'Tamarac, FL' },
  { id: 892, city: 'Tampa', state: 'FL', value: 'Tampa, FL' },
  { id: 893, city: 'Taunton', state: 'MA', value: 'Taunton, MA' },
  { id: 894, city: 'Taylor', state: 'MI', value: 'Taylor, MI' },
  { id: 895,
    city: 'Taylorsville',
    state: 'UT',
    value: 'Taylorsville, UT' },
  { id: 896, city: 'Temecula', state: 'CA', value: 'Temecula, CA' },
  { id: 897, city: 'Tempe', state: 'AZ', value: 'Tempe, AZ' },
  { id: 898, city: 'Temple', state: 'TX', value: 'Temple, TX' },
  { id: 899,
    city: 'Terre Haute',
    state: 'IN',
    value: 'Terre Haute, IN' },
  { id: 900,
    city: 'Texarkana',
    state: 'TX',
    value: 'Texarkana, TX' },
  { id: 901,
    city: 'Texas City',
    state: 'TX',
    value: 'Texas City, TX' },
  { id: 902,
    city: 'The Colony',
    state: 'TX',
    value: 'The Colony, TX' },
  { id: 903, city: 'Thornton', state: 'CO', value: 'Thornton, CO' },
  { id: 904,
    city: 'Thousand Oaks',
    state: 'CA',
    value: 'Thousand Oaks, CA' },
  { id: 905, city: 'Tigard', state: 'OR', value: 'Tigard, OR' },
  { id: 906,
    city: 'Tinley Park',
    state: 'IL',
    value: 'Tinley Park, IL' },
  { id: 907,
    city: 'Titusville',
    state: 'FL',
    value: 'Titusville, FL' },
  { id: 908, city: 'Toledo', state: 'OH', value: 'Toledo, OH' },
  { id: 909, city: 'Topeka', state: 'KS', value: 'Topeka, KS' },
  { id: 910, city: 'Torrance', state: 'CA', value: 'Torrance, CA' },
  { id: 911, city: 'Tracy', state: 'CA', value: 'Tracy, CA' },
  { id: 912, city: 'Trenton', state: 'NJ', value: 'Trenton, NJ' },
  { id: 913, city: 'Troy', state: 'MI', value: 'Troy, MI' },
  { id: 914, city: 'Troy', state: 'NY', value: 'Troy, NY' },
  { id: 915, city: 'Tucson', state: 'AZ', value: 'Tucson, AZ' },
  { id: 916, city: 'Tulare', state: 'CA', value: 'Tulare, CA' },
  { id: 917, city: 'Tulsa', state: 'OK', value: 'Tulsa, OK' },
  { id: 918, city: 'Turlock', state: 'CA', value: 'Turlock, CA' },
  { id: 919,
    city: 'Tuscaloosa',
    state: 'AL',
    value: 'Tuscaloosa, AL' },
  { id: 920, city: 'Tustin', state: 'CA', value: 'Tustin, CA' },
  { id: 921,
    city: 'Twin Falls',
    state: 'ID',
    value: 'Twin Falls, ID' },
  { id: 922, city: 'Tyler', state: 'TX', value: 'Tyler, TX' },
  { id: 923,
    city: 'Union City',
    state: 'CA',
    value: 'Union City, CA' },
  { id: 924,
    city: 'Union City',
    state: 'NJ',
    value: 'Union City, NJ' },
  { id: 925, city: 'Upland', state: 'CA', value: 'Upland, CA' },
  { id: 926, city: 'Urbana', state: 'IL', value: 'Urbana, IL' },
  { id: 927,
    city: 'Urbandale',
    state: 'IA',
    value: 'Urbandale, IA' },
  { id: 928, city: 'Utica', state: 'NY', value: 'Utica, NY' },
  { id: 929,
    city: 'Vacaville',
    state: 'CA',
    value: 'Vacaville, CA' },
  { id: 930, city: 'Valdosta', state: 'GA', value: 'Valdosta, GA' },
  { id: 931, city: 'Vallejo', state: 'CA', value: 'Vallejo, CA' },
  { id: 932,
    city: 'Valley Stream',
    state: 'NY',
    value: 'Valley Stream, NY' },
  { id: 933,
    city: 'Vancouver',
    state: 'WA',
    value: 'Vancouver, WA' },
  { id: 934, city: 'Victoria', state: 'TX', value: 'Victoria, TX' },
  { id: 935,
    city: 'Victorville',
    state: 'CA',
    value: 'Victorville, CA' },
  { id: 936, city: 'Vineland', state: 'NJ', value: 'Vineland, NJ' },
  { id: 937,
    city: 'Virginia Beach',
    state: 'VA',
    value: 'Virginia Beach, VA' },
  { id: 938, city: 'Visalia', state: 'CA', value: 'Visalia, CA' },
  { id: 939, city: 'Vista', state: 'CA', value: 'Vista, CA' },
  { id: 940, city: 'Waco', state: 'TX', value: 'Waco, TX' },
  { id: 941,
    city: 'Walnut Creek',
    state: 'CA',
    value: 'Walnut Creek, CA' },
  { id: 942, city: 'Waltham', state: 'MA', value: 'Waltham, MA' },
  { id: 943,
    city: 'Warner Robins',
    state: 'GA',
    value: 'Warner Robins, GA' },
  { id: 944, city: 'Warren', state: 'MI', value: 'Warren, MI' },
  { id: 945, city: 'Warren', state: 'OH', value: 'Warren, OH' },
  { id: 946, city: 'Warwick', state: 'RI', value: 'Warwick, RI' },
  { id: 947,
    city: 'Washington',
    state: undefined,
    value: 'Washington, undefined' },
  { id: 948,
    city: 'Waterbury',
    state: 'CT',
    value: 'Waterbury, CT' },
  { id: 949, city: 'Waterloo', state: 'IA', value: 'Waterloo, IA' },
  { id: 950,
    city: 'Watsonville',
    state: 'CA',
    value: 'Watsonville, CA' },
  { id: 951, city: 'Waukegan', state: 'IL', value: 'Waukegan, IL' },
  { id: 952, city: 'Waukesha', state: 'WI', value: 'Waukesha, WI' },
  { id: 953, city: 'Wausau', state: 'WI', value: 'Wausau, WI' },
  { id: 954,
    city: 'Wauwatosa',
    state: 'WI',
    value: 'Wauwatosa, WI' },
  { id: 955,
    city: 'Wellington',
    state: 'FL',
    value: 'Wellington, FL' },
  { id: 956, city: 'Weslaco', state: 'TX', value: 'Weslaco, TX' },
  { id: 957,
    city: 'West Allis',
    state: 'WI',
    value: 'West Allis, WI' },
  { id: 958,
    city: 'West Covina',
    state: 'CA',
    value: 'West Covina, CA' },
  { id: 959,
    city: 'West Des Moines',
    state: 'IA',
    value: 'West Des Moines, IA' },
  { id: 960,
    city: 'West Haven',
    state: 'CT',
    value: 'West Haven, CT' },
  { id: 961,
    city: 'West Jordan',
    state: 'UT',
    value: 'West Jordan, UT' },
  { id: 962,
    city: 'West New York',
    state: 'NJ',
    value: 'West New York, NJ' },
  { id: 963,
    city: 'West Palm Beach',
    state: 'FL',
    value: 'West Palm Beach, FL' },
  { id: 964,
    city: 'West Sacramento',
    state: 'CA',
    value: 'West Sacramento, CA' },
  { id: 965,
    city: 'West Valley City',
    state: 'UT',
    value: 'West Valley City, UT' },
  { id: 966,
    city: 'Westerville',
    state: 'OH',
    value: 'Westerville, OH' },
  { id: 967,
    city: 'Westfield',
    state: 'MA',
    value: 'Westfield, MA' },
  { id: 968, city: 'Westland', state: 'MI', value: 'Westland, MI' },
  { id: 969,
    city: 'Westminster',
    state: 'CO',
    value: 'Westminster, CO' },
  { id: 970,
    city: 'Westminster',
    state: 'CA',
    value: 'Westminster, CA' },
  { id: 971, city: 'Weston', state: 'FL', value: 'Weston, FL' },
  { id: 972,
    city: 'Weymouth Town',
    state: 'MA',
    value: 'Weymouth Town, MA' },
  { id: 973, city: 'Wheaton', state: 'IL', value: 'Wheaton, IL' },
  { id: 974, city: 'Wheeling', state: 'IL', value: 'Wheeling, IL' },
  { id: 975,
    city: 'White Plains',
    state: 'NY',
    value: 'White Plains, NY' },
  { id: 976, city: 'Whittier', state: 'CA', value: 'Whittier, CA' },
  { id: 977, city: 'Wichita', state: 'KS', value: 'Wichita, KS' },
  { id: 978,
    city: 'Wichita Falls',
    state: 'TX',
    value: 'Wichita Falls, TX' },
  { id: 979,
    city: 'Wilkes-Barre',
    state: 'PA',
    value: 'Wilkes-Barre, PA' },
  { id: 980,
    city: 'Wilmington',
    state: 'NC',
    value: 'Wilmington, NC' },
  { id: 981,
    city: 'Wilmington',
    state: 'DE',
    value: 'Wilmington, DE' },
  { id: 982, city: 'Wilson', state: 'NC', value: 'Wilson, NC' },
  { id: 983,
    city: 'Winston-Salem',
    state: 'NC',
    value: 'Winston-Salem, NC' },
  { id: 984,
    city: 'Winter Garden',
    state: 'FL',
    value: 'Winter Garden, FL' },
  { id: 985, city: 'Woburn', state: 'MA', value: 'Woburn, MA' },
  { id: 986, city: 'Woodbury', state: 'MN', value: 'Woodbury, MN' },
  { id: 987, city: 'Woodland', state: 'CA', value: 'Woodland, CA' },
  { id: 988,
    city: 'Woonsocket',
    state: 'RI',
    value: 'Woonsocket, RI' },
  { id: 989,
    city: 'Worcester',
    state: 'MA',
    value: 'Worcester, MA' },
  { id: 990, city: 'Wylie', state: 'TX', value: 'Wylie, TX' },
  { id: 991, city: 'Wyoming', state: 'MI', value: 'Wyoming, MI' },
  { id: 992, city: 'Yakima', state: 'WA', value: 'Yakima, WA' },
  { id: 993, city: 'Yonkers', state: 'NY', value: 'Yonkers, NY' },
  { id: 994,
    city: 'Yorba Linda',
    state: 'CA',
    value: 'Yorba Linda, CA' },
  { id: 995, city: 'York', state: 'PA', value: 'York, PA' },
  { id: 996,
    city: 'Youngstown',
    state: 'OH',
    value: 'Youngstown, OH' },
  { id: 997,
    city: 'Yuba City',
    state: 'CA',
    value: 'Yuba City, CA' },
  { id: 998, city: 'Yucaipa', state: 'CA', value: 'Yucaipa, CA' },
  { id: 999, city: 'Yuma', state: 'AZ', value: 'Yuma, AZ' } ]

export default cityList
